// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhCnUsfgY3grnI0cgbEBwvleVpP6O4o8Y',
    appId: '1:1073419960822:web:d32f208f5ca29c1b1747d7',
    messagingSenderId: '1073419960822',
    projectId: 'smart-india-hackathon-20-c6820',
    authDomain: 'smart-india-hackathon-20-c6820.firebaseapp.com',
    storageBucket: 'smart-india-hackathon-20-c6820.appspot.com',
    measurementId: 'G-BWD0YJJ9NT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz3pH5ElGKwBGP8ggp04t9IYiqFSfmWIs',
    appId: '1:1073419960822:android:669a9a827a501e841747d7',
    messagingSenderId: '1073419960822',
    projectId: 'smart-india-hackathon-20-c6820',
    storageBucket: 'smart-india-hackathon-20-c6820.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8b4SO_PeO_bxT5hfmYnuSaSf-my-RNqs',
    appId: '1:1073419960822:ios:5023b538f8b4278b1747d7',
    messagingSenderId: '1073419960822',
    projectId: 'smart-india-hackathon-20-c6820',
    storageBucket: 'smart-india-hackathon-20-c6820.appspot.com',
    iosBundleId: 'com.innovision.smartIndiaHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8b4SO_PeO_bxT5hfmYnuSaSf-my-RNqs',
    appId: '1:1073419960822:ios:14d662f0bab6199c1747d7',
    messagingSenderId: '1073419960822',
    projectId: 'smart-india-hackathon-20-c6820',
    storageBucket: 'smart-india-hackathon-20-c6820.appspot.com',
    iosBundleId: 'com.innovision.smartIndiaHackathon.RunnerTests',
  );
}
